package com.example.perpus.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.perpus.repository.RepositoryBuku
import com.example.perpus.repository.RepositoryTransaksi
import com.example.perpus.room.Buku
import com.example.perpus.room.Transaksi
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.time.LocalDateTime
import java.util.Date
import java.util.Locale

class TransaksiViewModel(
	private val repositoryTransaksi: RepositoryTransaksi,
	private val repositoryBuku: RepositoryBuku
) : ViewModel() {

	private val _transaksiAktif = MutableStateFlow<List<Transaksi>>(emptyList())
	val transaksiAktif = _transaksiAktif.asStateFlow()

	init {
		loadTransaksiAktif()
		loadDaftarBuku()
	}

	private val _daftarBuku = MutableStateFlow<List<Buku>>(emptyList())
	val daftarBuku = _daftarBuku.asStateFlow()


	private fun loadTransaksiAktif() {
		viewModelScope.launch {
			try {
				val list = repositoryTransaksi.getTransaksiAktif()
				_transaksiAktif.value = list
			} catch (e: Exception) {
				// Handle error
			}
		}
	}

	private fun loadDaftarBuku() {
		viewModelScope.launch {
			try {
				val list = repositoryBuku.getAllBukuStatic()
				_daftarBuku.value = list
			} catch (e: Exception) {
			}
		}
	}


	fun kembalikanBuku(idTransaksi: Int, onComplete: () -> Unit = {}) {
		viewModelScope.launch {
			try {
				val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
				val tanggalKembali = dateFormat.format(Date())

				repositoryTransaksi.selesaikanPengembalian(idTransaksi, tanggalKembali)

				loadTransaksiAktif()

				onComplete()
			} catch (e: Exception) {
			}
		}
	}

	fun tambahPeminjaman(
		namaAnggota: String,
		idBuku: Int,
		tanggal: LocalDateTime,
		judulBuku: String
	) {
		val transaksiBaru = Transaksi(
			id = 0, // Auto-generated by Room
			judulBuku = judulBuku,
			namaAnggota = namaAnggota,
			idBuku = idBuku,
			tanggalPinjam = getCurrentDate(),
			status = "aktif"
		)
		viewModelScope.launch {
			repositoryTransaksi.insertTransaksi(transaksiBaru)
			loadTransaksiAktif()
		}
	}

	fun hapusTransaksi(id: Int) {
		viewModelScope.launch {
			repositoryTransaksi.hapusTransaksi(id)
		}
	}

	// Di dalam class TransaksiViewModel
	fun tambahTransaksi(transaksi: Transaksi) {
		viewModelScope.launch {
			repositoryTransaksi.insertTransaksi(transaksi)
			loadTransaksiAktif()
		}
	}

	fun updateTransaksi(transaksi: Transaksi) {
		viewModelScope.launch {
			repositoryTransaksi.updateTransaksi(transaksi)
			loadTransaksiAktif()
		}
	}

	suspend fun getTransaksiById(id: Int): Transaksi? {
		return repositoryTransaksi.getTransaksiById(id)
	}

	private fun getCurrentDate(): String {
		return SimpleDateFormat("dd/MM/yyyy", Locale.getDefault()).format(Date())
	}

}
